# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^rqml_core/assets/
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
        exclude: ^third_party/
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
        exclude: ^third_party/
      - id: mixed-line-ending
        exclude: ^third_party/
      - id: trailing-whitespace
        exclude_types: [rst, markdown]
        exclude: ^third_party/

  # CPP Checks
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.7
    hooks:
      - id: clang-format
        name: Clang Format
        args: [--style=file]
        files: \.(cpp|hpp|h|c|cc)$
        exclude: ^third_party/

  - repo: local
    hooks:
      - id: cppcheck
        name: Cppcheck
        entry: bash -c "cppcheck --force --library=qt --quiet --inline-suppr --error-exitcode=1 --language=c++ $(find . -type d \( -name 'cmake-build-*' -o -name 'third_party' \) -prune -false -o -name '*.cpp' -o -name '*.hpp' -o -name '*.h' -o -name '*.c' -o -name '*.cc')"
        language: system
        files: \.(cpp|cc|hpp|h)$
        pass_filenames: false

  # CMake Formatting
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-lint
      exclude: ^third_party/

  # Package XML
  - repo: https://github.com/Joschi3/package_xml_validation.git
    rev: v1.3.0
    hooks:
      - id: format-package-xml
        name: Validate and Format package.xml
        exclude: ^third_party/

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.35.0
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
      - id: check-github-actions
        args: ["--verbose"]
      - id: check-gitlab-ci
        args: ["--verbose"]
      - id: check-compose-spec
        args: ["--verbose"]

  - repo: local
    hooks:
      - id: qmlformat
        name: qmlformat
        entry: qmlformat
        language: system
        pass_filenames: true
        # The -i flag formats the file in-place
        # The optional -n flag normalizes the object attribute order based on Qt conventions
        args: [-n, -i]
        files: \.qml$
