name: Lint, Build & Test
on:
  push:
    branches:
      - rolling
  pull_request:
    branches:
      - rolling
defaults:
  run:
    shell: bash

jobs:
  Linting:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        run: | # qmlformat is in the dev tools
          sudo apt-get update && sudo apt-get install -y clang-format cppcheck libxml2-utils qt6-declarative-dev-tools
          sudo ln -s /usr/lib/qt6/bin/qmlformat /usr/local/bin/qmlformat

      - name: Install and Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  build-and-test:
    needs: Linting
    strategy:
      matrix:
        setup:
          - rosdistro: jazzy
            os: ubuntu-24.04
          - rosdistro: rolling
            os: ubuntu-latest
    runs-on: ${{ matrix.setup.os }}
    container:
      image: ros:${{ matrix.setup.rosdistro }}-ros-base
    steps:
      - name: install build tools and latest testing repo
        run: |
          sudo apt-get update
          sudo apt-get install -y ros-dev-tools ros2-testing-apt-source
          sudo apt-get update
      - uses: actions/checkout@v4
        with:
          path: src/repo
      - name: rosdep
        run: |
          rosdep update --rosdistro ${{ matrix.setup.rosdistro }} --include-eol-distros
          rosdep install -y --from-paths src --ignore-src --rosdistro ${{ matrix.setup.rosdistro }}
      - name: build
        run: |
          source /opt/ros/${{ matrix.setup.rosdistro }}/setup.bash
          colcon build
      - name: test
        run: |
          source /opt/ros/${{ matrix.setup.rosdistro }}/setup.bash
          colcon test --packages-select rqml_core rqml_default_plugins
          colcon test-result --verbose
